twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        nomBlog: "Blog COURREJOU"
        categoryRepository: "@App\\Repository\\CategoryRepository"
        typeRepository: "@App\\Repository\\TypeRepository"
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
