controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
#routingTest:
#    path: /blog/description
#    controller: App\Controller\BlogController::routingTest
